---

 - name: PLAY1 - GENERATE SCRIPTS FOR DALIA
   hosts: monterrey
   gather_facts: false
   connection: local
  
   tasks:

      - name: GENERATE CONFIGS FOR EACH OS
        template:
          src: "./templates/{{ os }}.j2"
          dest: "./templates/configs/{{ inventory_hostname }}.txt"